import {evaluate_json,minimize_json} from './agent_tape.js';
const $=id=>document.getElementById(id);let last=null;
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function render(r){last=r;$('report').textContent=JSON.stringify(r,null,2);$('calls').textContent=r.calls??'—';$('cost').textContent=r.total_cost??'—';$('network').textContent=r.network_calls??'—';$('status').textContent=r.error?r.error:r.ok?'通过 · 可重复回放':'未通过 · 发现违规';$('status').className='status'+(r.ok?'':' bad');$('events').replaceChildren();(r.violations||[]).forEach(v=>{const d=node('div','','event bad');d.append(node('b',v.code+' / '+v.event_id),node('p','步骤 '+v.step+' · '+v.message));$('events').append(d)});(r.replay||[]).forEach(x=>{const d=node('div','','event');d.append(node('b',x.event_id+' → '+x.tool),node('p','fixture: '+x.result));$('events').append(d)})}
function run(){try{$('error').textContent='';$('reduction').replaceChildren();render(JSON.parse(evaluate_json($('tape').value)))}catch(e){$('error').textContent=e.message}}
async function load(n){try{const r=await fetch('./fixtures/'+n+'.json');if(!r.ok)throw Error('示例加载失败');$('tape').value=JSON.stringify(await r.json(),null,2);run()}catch(e){$('error').textContent=e.message}}
$('bad').onclick=()=>load('missing-approval');$('good').onclick=()=>load('approved');$('drift').onclick=()=>load('drift');$('evaluate').onclick=run;
$('reduce').onclick=()=>{try{const r=JSON.parse(minimize_json($('tape').value));$('reduction').replaceChildren();if(r.error||r.message){$('reduction').append(node('p',r.error||r.message));return}render(r.report);last=r;$('reduction').append(node('h2',`缩减 ${r.before} → ${r.after} 个事件`),node('p','保留违规类型：'+r.target_code),node('pre',JSON.stringify(r.tape.events,null,2)))}catch(e){$('error').textContent=e.message}};
$('download').onclick=()=>{if(!last)return;const u=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}));const a=node('a','');a.href=u;a.download='agent-tape-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};load('missing-approval');
